### ISSUE TITLE
[ProcessManagement] Implement process scheduler

### ISSUE THREAD

**Issue by wake-0** [Blackjack92/fhvOS#28] opened 2015-04-01 07:59 UTC
Implement a default process scheduler without mmu.

**Comment by wake-0** [comment] 2015-04-15 10:38
Sample code for starting a timer for the scheduler:

```
DriverManagerInit();

SchedulerInit();
SchedulerStartProcess(&led1);
SchedulerStartProcess(&led2);

timer2 = DeviceManagerGetDevice("TIMER2", 6);
DeviceManagerInitDevice(timer2);

device_t cpu = DeviceManagerGetDevice("CPU", 3);
DeviceManagerIoctl(cpu, DRIVER_CPU_COMMAND_INTERRUPT_MASTER_IRQ_ENABLE, 0, NULL, 0);
DeviceManagerIoctl(cpu, DRIVER_CPU_COMMAND_INTERRUPT_RESET_AINTC, 0, NULL, 0);

uint16_t timeInMilis = 1;
uint16_t interruptMode = 0x02; // overflow
uint16_t priority = 0x1;

DeviceManagerIoctl(timer2, timeInMilis, interruptMode, (char*) timerISR, priority);
DeviceManagerOpen(timer2);
```

**Comment by trylimits** [comment] 2015-04-30 18:03
It seems like the last commit fixes all the problems we had.

I'm not sure if we should close this ticket and open a new one if we face some issues with the context switch. @Blackjack92 Pls decide this

**Comment by trylimits** [comment] 2015-05-01 09:42
I did some refactoring in the scheduler, i.e. I moved the timer initialization and timer isr to the scheduler code.

Furthermore, I have implemented a third process which ends after one iteration and improved the scheduler to handle this case.

The scheduler runs perfectly fine for at least 10 minutes thus fulfilling the requirements :)

**Comment by ghost** [comment] 2015-05-01 10:26
do you know why the scheduler crashes after 10mins? is it still the stack overwriting problem?

**Comment by trylimits** [comment] 2015-05-01 11:24
It does not crash after 10 mins. I just tested it until it crashes and it was approx. after one hour. And yes, imo it is caused by not restoring the stack pointer properly if the scheduler performs a context switch. I suggest to open a new ticket for that issue.

**Closed as completed by trylimits** 2015-05-01 11:24 UTC
Labels: done

**Comment by ghost** [comment] 2015-05-01 14:48
Take a look at the last line in the restore registers function:

RestoreRegisters:
    ADD      SP, SP, #40
    LDMFD    SP!, {CPSR}

```
LDMFD    SP, {R13}^
NOP
ADD      SP, SP, #4
;LDMFD   SP!, {SP}
LDMFD    SP, {R0-R12, PC}^
;ADD         SP, SP, #56
```

We are restoring the registers without correcting the stack pointer. Then the relative slow crash after about an hour would make sense. What do you think?
I'm sorry that I can't test it, I'm currently not st home.

**Comment by trylimits** [comment] 2015-05-01 15:26
Further discussion in Bug #44
